### ISSUE TITLE
Question regarding 6sockets

### ISSUE THREAD

**Issue by Cloudslapper** [darvid/wraeblast#8]
The filter is currently showing 6Sockets even on Q5, even though they're practically worthless.
Is this by choice or is it an oversight?

on Q4+, an awakened sextant being 1.7-2c is hidden, while the 6socket is shown.

**Comment by darvid** [comment]
yeah the trade filter needs quite a bit of work, I haven't had a ton of time to work through all the kinks but I plan on adding some additional filter variants, hopefully soon.

* 6sockets (and 6 links, although those are probably safe to always show) are the only hard-coded recipes I included in the trade filter, since they can be valuable early league - the proper way to automate showing/hiding them between quantiles would be to assign them the value of 6 jeweller's orbs or something like that, and I just haven't gotten around to it.
* anything being hidden is intended as it probably doesn't show up in that quantile based on current poe.ninja data. the trade filter currently does not use any sorts of hard-coded thresholds like 1c. 

there should only be one entry in the generated filter for the 6 sockets, so you can search for `six-socket.mp3` and hide them for now. 

in terms of the broader subject of the trade filter needing improvement at the moment, here are some of the things I've noticed and plan to address by providing additional variants, feel free to comment or add to the list:

* essences probably make sense to just universally show, at least in a separate variant, given the fact that harvest/essence farming strategies involve converting shit essences to good ones, so it's probably worthwhile picking the higher tiers up even if they are in the low quantiles
* map currency probably makes sense to universally show, except for chisels (unless they're in big enough stacks) - sextants can be upgraded, sac fragments, low tier/shit scarabs for harvest conversion/vendor recipe/mapping fodder, etc.; perhaps it makes sense to have a generic "mapping" variant?
* nem3 definitely needs its own variant, the bulk of the profit is literally picking up low value currency
* legion farming probably needs its own variant

the trouble is figuring out where variants overlap, finding a decent common ground for the generic trade filter, and determining whether or not it makes sense for some/all of these variants to also have permutations of quantiles. I'm going to try and come up with whatever is simplest and quickest to get something usable out soon, but feedback is appreciated from anyone who daily drives the filter(s) since I don't want to make assumptions for everyone.

**Comment by Cloudslapper** [comment]
Alright :) thanks for the in depth answer, much appreciated
Still truly love this filter and have been running it regardless of the issues, with minor tweaks where i needed them.
I'll do a proper run for a few days and throw you some proper feedback

**Comment by darvid** [comment]
FYI six sockets should now be hidden (starting with the nightly for today, 11/9) in the trade filter
